In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

In [ ]:
iris = load_iris()

In [ ]:
x= iris.data
y= iris.target

In [ ]:
scaler = StandardScaler()

In [ ]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
x_scaled = scaler.fit_transform(x)


In [ ]:
covariance_mtx = np.cov(x_scaled.T)
covariance_mtx

array([[ 1.00671141, -0.11835884,  0.87760447,  0.82343066],
       [-0.11835884,  1.00671141, -0.43131554, -0.36858315],
       [ 0.87760447, -0.43131554,  1.00671141,  0.96932762],
       [ 0.82343066, -0.36858315,  0.96932762,  1.00671141]])

In [ ]:
eig_vals, eig_vec = np.linalg.eig(covariance_mtx)
print('Eigen Values')
print(eig_vals)
print()
print('Eigen Vectors')
print(eig_vec)

Eigen Values
[2.93808505 0.9201649  0.14774182 0.02085386]

Eigen Vectors
[[ 0.52106591 -0.37741762 -0.71956635  0.26128628]
 [-0.26934744 -0.92329566  0.24438178 -0.12350962]
 [ 0.5804131  -0.02449161  0.14212637 -0.80144925]
 [ 0.56485654 -0.06694199  0.63427274  0.52359713]]


In [ ]:
total  =sum(eig_vals)
var_exp = [ i/total*100 for i in eig_vals]
var_exp

[72.96244541329989, 22.850761786701753, 3.668921889282865, 0.5178709107154905]

In [ ]:
x_pca = x_scaled.dot(eig_vec[:,:3])
x_pca[:5]

array([[-2.26470281, -0.4800266 , -0.12770602],
       [-2.08096115,  0.67413356, -0.23460885],
       [-2.36422905,  0.34190802,  0.04420148],
       [-2.29938422,  0.59739451,  0.09129011],
       [-2.38984217, -0.64683538,  0.0157382 ]])

In [ ]:
pca_sklearn = PCA(n_components = 3)
x_pca_sklearn = pca_sklearn.fit_transform(x_scaled)
print(x_pca_sklearn[:5])
print(x_pca_sklearn.shape)

[[-2.26470281  0.4800266   0.12770602]
 [-2.08096115 -0.67413356  0.23460885]
 [-2.36422905 -0.34190802 -0.04420148]
 [-2.29938422 -0.59739451 -0.09129011]
 [-2.38984217  0.64683538 -0.0157382 ]]
(150, 3)


In [ ]:
eigen_valu = pca_sklearn.explained_variance_
eigen_valu

array([2.93808505, 0.9201649 , 0.14774182])

In [ ]:
# with original data
model = LogisticRegression()
model.fit(x_scaled,y)
y_pred = model.predict(x_scaled)
print(accuracy_score(y,y_pred))


0.9733333333333334


In [ ]:
# with feature extraction applying PCA from scratch
model_pca_scratch = LogisticRegression()
model_pca_scratch.fit(x_pca,y)
y_pred_pca =model_pca_scratch.predict(x_pca)
print(accuracy_score(y,y_pred_pca))


0.9733333333333334


In [ ]:
# with feature extraction with the help of sklearn
model_pca_sklearn = LogisticRegression()
model_pca_sklearn.fit(x_pca_sklearn,y)
y_pred_pca_sklearn =model_pca_sklearn.predict(x_pca_sklearn)
print(accuracy_score(y,y_pred_pca_sklearn))


0.9733333333333334
